// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// DocsResponse defines model for DocsResponse.
type DocsResponse = string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status *string `json:"status,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Id       *string              `json:"id,omitempty"`
	Username *string              `json:"username,omitempty"`
}

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// RegisterUserJSONBody defines parameters for RegisterUser.
type RegisterUserJSONBody struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Password *string              `json:"password,omitempty"`
	Username *string              `json:"username,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody LoginUserJSONBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody RegisterUserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check API status
	// (GET /api/v1/)
	GetApiStatus(c *gin.Context)
	// Serve Swagger UI entrypoint
	// (GET /api/v1/docs)
	GetSwaggerIndex(c *gin.Context)
	// Serve Swagger UI entrypoint with trailing slash
	// (GET /api/v1/docs/)
	GetSwaggerIndexWithSlash(c *gin.Context)
	// Download the OpenAPI specification file
	// (GET /api/v1/docs/openapi.yaml)
	GetOpenApiDocument(c *gin.Context)
	// Authenticate a user and return a token
	// (POST /api/v1/login)
	LoginUser(c *gin.Context)
	// Get the authenticated user's profile information
	// (GET /api/v1/my-info)
	GetMyInfo(c *gin.Context)
	// Register a new user
	// (POST /api/v1/register)
	RegisterUser(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiStatus operation middleware
func (siw *ServerInterfaceWrapper) GetApiStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiStatus(c)
}

// GetSwaggerIndex operation middleware
func (siw *ServerInterfaceWrapper) GetSwaggerIndex(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSwaggerIndex(c)
}

// GetSwaggerIndexWithSlash operation middleware
func (siw *ServerInterfaceWrapper) GetSwaggerIndexWithSlash(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSwaggerIndexWithSlash(c)
}

// GetOpenApiDocument operation middleware
func (siw *ServerInterfaceWrapper) GetOpenApiDocument(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenApiDocument(c)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c)
}

// GetMyInfo operation middleware
func (siw *ServerInterfaceWrapper) GetMyInfo(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyInfo(c)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterUser(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/", wrapper.GetApiStatus)
	router.GET(options.BaseURL+"/api/v1/docs", wrapper.GetSwaggerIndex)
	router.GET(options.BaseURL+"/api/v1/docs/", wrapper.GetSwaggerIndexWithSlash)
	router.GET(options.BaseURL+"/api/v1/docs/openapi.yaml", wrapper.GetOpenApiDocument)
	router.POST(options.BaseURL+"/api/v1/login", wrapper.LoginUser)
	router.GET(options.BaseURL+"/api/v1/my-info", wrapper.GetMyInfo)
	router.POST(options.BaseURL+"/api/v1/register", wrapper.RegisterUser)
}
